name: sh-dog

services:
  train:
    image: ${SH_DOG_TRAIN_IMAGE:-sh-dog:train}
    build:
      context: ..
      dockerfile: docker/Dockerfile.train
      target: training
      network: host

    gpus: all
    shm_size: ${SH_DOG_SHM_SIZE:-2gb}

    environment:
      ACCEPT_EULA: "Y"
      PRIVACY_CONSENT: ${PRIVACY_CONSENT:-Y}
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /workspace/sh_dog/training/source/sh_dog

    entrypoint: ["/bin/bash", "/workspace/sh_dog/docker/entrypoint.train.sh"]

    volumes:
      - type: bind
        source: ..
        target: /workspace/sh_dog
